//! Consensus namespace RPC implementation.
#![allow(clippy::double_must_use)] // Async methods generated by `rpc` add `must_use`.
//!
//! Provides query methods and subscriptions for consensus data:
//! - `consensus_getFinalization(query)` - Get finalization by height from marshal archive
//! - `consensus_getLatest()` - Get the current consensus state snapshot
//! - `consensus_subscribe()` - Subscribe to consensus events stream
//! - `consensus_getEquivocations()` - Evidence this node holds of conflicting votes
//! - `consensus_getDisputedRounds()` - Rounds whose votes disagree at this node
//! - `consensus_getVotes(round)` - The signed votes this node holds for a round

pub mod types;

#[cfg(test)]
mod tests;

use alloy_primitives::Bytes;
use jsonrpsee::{
    core::RpcResult,
    proc_macros::rpc,
    types::{ErrorObject, error::INTERNAL_ERROR_CODE},
};

pub use types::{CertifiedBlock, ConsensusFeed, ConsensusState, Event, Query, RoundId, SignedVote};

/// Custom error codes for the consensus RPC.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(i32)]
pub enum ErrorCode {
    NoContent = 204,
    ServiceUnavailable = 503,
}

impl ErrorCode {
    fn msg(self) -> &'static str {
        match self {
            Self::NoContent => "the requested content was not available",
            Self::ServiceUnavailable => {
                "the consensus subservice was not available, but the request can be retried later"
            }
        }
    }
}

impl<T> From<types::Response<T>> for RpcResult<T> {
    fn from(value: types::Response<T>) -> Self {
        match value {
            types::Response::Success(val) => Ok(val),
            types::Response::NotReady => Err(ErrorObject::owned(
                ErrorCode::NoContent as i32,
                ErrorCode::NoContent.msg(),
                None::<()>,
            )),
            types::Response::Missing(msg) => Err(ErrorObject::owned(
                ErrorCode::ServiceUnavailable as i32,
                ErrorCode::ServiceUnavailable.msg(),
                Some(msg),
            )),
        }
    }
}

/// Consensus namespace RPC trait.
#[rpc(server, client, namespace = "consensus")]
pub trait TempoConsensusApi {
    /// Get finalization by height query.
    ///
    /// Use `"latest"` to get the most recent finalization, or `{"height": N}` for a specific height.
    #[method(name = "getFinalization")]
    async fn get_finalization(&self, query: Query) -> RpcResult<CertifiedBlock>;

    /// Get the current consensus state snapshot.
    ///
    /// Returns the latest finalized block. The notarized field is retained for compatibility.
    #[method(name = "getLatest")]
    async fn get_latest(&self) -> RpcResult<ConsensusState>;

    /// Subscribe to finalized block events.
    #[subscription(name = "subscribe" => "event", unsubscribe = "unsubscribe", item = Event)]
    async fn subscribe_events(&self) -> jsonrpsee::core::SubscriptionResult;

    /// Get the evidence this node holds of validators that signed conflicting votes, encoded.
    ///
    /// Empty unless votes carry their signer's signature (`attributableVotesTime`).
    #[method(name = "getEquivocations")]
    async fn get_equivocations(&self) -> RpcResult<Vec<Bytes>>;

    /// Get the rounds whose votes disagree at this node.
    ///
    /// A validator may have sent another node a vote that conflicts with one held here.
    #[method(name = "getDisputedRounds")]
    async fn get_disputed_rounds(&self) -> RpcResult<Vec<RoundId>>;

    /// Get the signed votes this node holds for a round.
    #[method(name = "getVotes")]
    async fn get_votes(&self, round: RoundId) -> RpcResult<Vec<SignedVote>>;
}

/// Tempo consensus RPC implementation.
#[derive(Debug, Clone)]
pub struct TempoConsensusRpc<I> {
    consensus_feed: I,
}

impl<I: ConsensusFeed> TempoConsensusRpc<I> {
    /// Create a new consensus RPC handler.
    pub fn new(consensus_feed: I) -> Self {
        Self { consensus_feed }
    }
}

#[async_trait::async_trait]
impl<I: ConsensusFeed> TempoConsensusApiServer for TempoConsensusRpc<I> {
    async fn get_finalization(&self, query: Query) -> RpcResult<CertifiedBlock> {
        self.consensus_feed.get_finalization(query).await.into()
    }

    async fn get_latest(&self) -> RpcResult<ConsensusState> {
        Ok(self.consensus_feed.get_latest().await)
    }

    async fn get_equivocations(&self) -> RpcResult<Vec<Bytes>> {
        Ok(self.consensus_feed.equivocations())
    }

    async fn get_disputed_rounds(&self) -> RpcResult<Vec<RoundId>> {
        Ok(self.consensus_feed.disputed_rounds())
    }

    async fn get_votes(&self, round: RoundId) -> RpcResult<Vec<SignedVote>> {
        Ok(self.consensus_feed.votes(round))
    }

    async fn subscribe_events(
        &self,
        pending: jsonrpsee::PendingSubscriptionSink,
    ) -> jsonrpsee::core::SubscriptionResult {
        let sink = pending.accept().await?;
        let mut rx = self.consensus_feed.subscribe().await.ok_or_else(|| {
            ErrorObject::owned(INTERNAL_ERROR_CODE, "Failed to subscribe", None::<()>)
        })?;

        tokio::spawn(async move {
            loop {
                // Events only arrive on finalization, so a failed `send` alone would not detect
                // a disconnect or unsubscribe while finalization is stalled. Race against
                // `closed()` so the task (and its subscription permit) is released promptly.
                let recv = tokio::select! {
                    _ = sink.closed() => break,
                    recv = rx.recv() => recv,
                };
                match recv {
                    Ok(event) => {
                        let msg = jsonrpsee::SubscriptionMessage::new(
                            sink.method_name(),
                            sink.subscription_id().clone(),
                            &event,
                        )
                        .expect("Event should be serializable");
                        if sink.send(msg).await.is_err() {
                            break;
                        }
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => continue,
                }
            }
        });

        Ok(())
    }
}
