//! `anchoring_searchRegistriesByName`: the index says which registries match, the contract
//! says what each one is. Only the page returned is read out of state.

#![allow(clippy::double_must_use)] // Async methods generated by `rpc` add `must_use`.

use alloy_primitives::{Address, B256};
use jsonrpsee::{core::RpcResult, proc_macros::rpc};
use reth_node_core::rpc::result::{internal_rpc_err, invalid_params_rpc_err};
use reth_storage_api::StateProviderFactory;
use serde::{Deserialize, Serialize};

use crate::{
    state::{self, Registry, Storage},
    store::{Mode, Reader},
};

/// `defaultPageLimit` and `maxPageLimit`, as the module's query server had them.
const DEFAULT_LIMIT: u64 = 50;
const MAX_LIMIT: u64 = 200;

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchParams {
    /// Matched case-insensitively in every mode.
    pub name: String,
    /// `exact` (the default), `prefix`, `suffix` or `contains`.
    #[serde(default)]
    pub mode: Mode,
    /// Matches to skip; matches come by id.
    #[serde(default)]
    pub offset: u64,
    /// 50 by default, 200 at most.
    #[serde(default)]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchResponse {
    pub registries: Vec<Registry>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IndexStatus {
    /// The highest registry id indexed.
    pub last_id: u64,
    /// How many the contract holds; the difference is what the index has yet to read.
    pub registry_count: u64,
    /// The block the index was last brought level with, once one has arrived.
    pub block_number: Option<u64>,
    pub block_hash: Option<B256>,
}

#[rpc(server, namespace = "anchoring")]
pub trait AnchoringApi {
    /// Registries whose name matches, by id. The contract answers an exact name itself;
    /// prefix, suffix and contains are what the index adds.
    #[method(name = "searchRegistriesByName")]
    async fn search_registries_by_name(&self, params: SearchParams) -> RpcResult<SearchResponse>;

    /// How far the index reaches.
    #[method(name = "nameIndexStatus")]
    async fn name_index_status(&self) -> RpcResult<IndexStatus>;
}

/// The `anchoring_` handlers, registered only on a node running the index.
#[derive(Clone, Debug)]
pub struct AnchoringRpc<Provider> {
    provider: Provider,
    index: Reader,
    contract: Address,
}

impl<Provider> AnchoringRpc<Provider> {
    pub const fn new(provider: Provider, index: Reader, contract: Address) -> Self {
        Self {
            provider,
            index,
            contract,
        }
    }
}

impl<Provider: StateProviderFactory> AnchoringRpc<Provider> {
    fn search(&self, params: SearchParams) -> RpcResult<SearchResponse> {
        if params.name.is_empty() {
            return Err(invalid_params_rpc_err("name must be provided"));
        }
        let limit = match params.limit.unwrap_or(DEFAULT_LIMIT) {
            0 => DEFAULT_LIMIT,
            limit => limit.min(MAX_LIMIT),
        };

        let ids = self
            .index
            .search(params.mode, &params.name, params.offset, limit)
            .map_err(internal)?;

        let state = self.provider.latest().map_err(internal)?;
        let words = Storage::new(&*state, self.contract);
        // The index can be a block ahead of a reorg that took a registry back; the count
        // keeps such an id out of the answer rather than hydrating it empty.
        let count = state::registry_count(&words).map_err(internal)?;
        let registries = ids
            .into_iter()
            .filter(|id| *id <= count)
            .map(|id| state::registry(&words, id))
            .collect::<eyre::Result<Vec<_>>>()
            .map_err(internal)?;

        Ok(SearchResponse { registries })
    }

    fn status(&self) -> RpcResult<IndexStatus> {
        let state = self.provider.latest().map_err(internal)?;
        let count =
            state::registry_count(&Storage::new(&*state, self.contract)).map_err(internal)?;
        let tip = self.index.tip().map_err(internal)?;
        Ok(IndexStatus {
            last_id: self.index.last_id().map_err(internal)?,
            registry_count: count,
            block_number: tip.map(|tip| tip.block_num),
            block_hash: tip.map(|tip| tip.hash),
        })
    }
}

#[async_trait::async_trait]
impl<Provider> AnchoringApiServer for AnchoringRpc<Provider>
where
    Provider: StateProviderFactory + Clone + Send + Sync + 'static,
{
    async fn search_registries_by_name(&self, params: SearchParams) -> RpcResult<SearchResponse> {
        let this = self.clone();
        blocking(move || this.search(params)).await
    }

    async fn name_index_status(&self) -> RpcResult<IndexStatus> {
        let this = self.clone();
        blocking(move || this.status()).await
    }
}

/// RocksDB and the state provider both block; the RPC threads answer every other method.
async fn blocking<T, F>(work: F) -> RpcResult<T>
where
    F: FnOnce() -> RpcResult<T> + Send + 'static,
    T: Send + 'static,
{
    tokio::task::spawn_blocking(work)
        .await
        .map_err(|error| internal_rpc_err(error.to_string()))?
}

fn internal(error: impl std::fmt::Display) -> jsonrpsee::types::ErrorObjectOwned {
    internal_rpc_err(error.to_string())
}
